services:
  db:
    container_name: anylistDB
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  anylistapp:
    container_name: anylistapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    image: nest-graphql
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"

    environment:
      STATE : ${STATE}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION : ${JWT_EXPIRATION}